{{ config(materialized='view') }}

WITH TRANSACTION_ITEMS AS (
    SELECT 
    ORDER_ITEM_ICEBERG.ORDER_ID,
    TRANSACTION_ICEBERG.FK_PERSON_ID AS PERSON_ID,
    ORDER_ITEM_ICEBERG.FK_PRODUCT_ID AS PRODUCT_ID,
    ORDER_ITEM_ICEBERG.FK_TRANSACTION_ID AS TRANSACTION_ID,
    ORDER_ITEM_ICEBERG.NUMBER_OF_PRODUCTS,
    ORDER_ITEM_ICEBERG.PRICE,
    TRANSACTION_ICEBERG.CREATED_AT AS TRANSACTION_DATE
    FROM ORDER_ITEM_ICEBERG
    JOIN TRANSACTION_ICEBERG ON ORDER_ITEM_ICEBERG.FK_TRANSACTION_ID = TRANSACTION_ICEBERG.TRANSACTION_ID
),
-- SELECT * FROM TRANSACTION_ITEMS;

ENRICHED_TRANSACTION AS (

    SELECT 
        TRANSACTION_ITEMS.ORDER_ID,
        TRANSACTION_ITEMS.PERSON_ID,
        TRANSACTION_ITEMS.PRODUCT_ID,
        TRANSACTION_ITEMS.TRANSACTION_ID,
        TRANSACTION_ITEMS.NUMBER_OF_PRODUCTS,
        TRANSACTION_ITEMS.PRICE,
        TRANSACTION_ITEMS.TRANSACTION_DATE,
        DATE_TRUNC('day', TRANSACTION_ITEMS.TRANSACTION_DATE) as DATE_KEY,
        PERSON_ICEBERG.FIRST_NAME,
        PERSON_ICEBERG.LAST_NAME,
        PERSON_ICEBERG.EMAIL,
        PRODUCT_ICEBERG.PRODUCT_NAME,
        
    FROM TRANSACTION_ITEMS
    JOIN PRODUCT_ICEBERG ON PRODUCT_ICEBERG.PRODUCT_ID = TRANSACTION_ITEMS.PRODUCT_ID
    JOIN PERSON_ICEBERG ON PERSON_ICEBERG.PERSON_ID = TRANSACTION_ITEMS.PERSON_ID
        

)
SELECT * FROM ENRICHED_TRANSACTION